export const SET_ERROR = "SET_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const IMPORT_CONCILIACAO = 'IMPORT_CONCILIACAO';
export const IMPORT_CONCILIACAO_SUCCESS = 'IMPORT_CONCILIACAO_SUCCESS';
export const LIST_CONCILIACAO = "LIST_CONCILIACAO";
export const LIST_CONCILIACAO_SUCCESS = "LIST_CONCILIACAO_SUCCESS";
export const GET_CONCILIACAO = "GET_CONCILIACAO";
export const GET_CONCILIACAO_SUCCESS = "GET_CONCILIACAO_SUCCESS";
export const RESET_CONCILIACAO = "RESET_CONCILIACAO";
export const REQUEST_CONCILIACAO_FAILURE = 'REQUEST_CONCILIACAO_FAILURE';

/*FATURAMENTO */
export const FAT_CHECKOUT_READ = 'FAT_CHECKOUT_READ';
export const FAT_CHECKOUT_SAVE = "FAT_CHECKOUT_SAVE";
export const FAT_EXPORT_FOB_SUCCESS = "FAT_EXPORT_FOB_SUCCESS";
export const FAT_EXPORT_FOB_CLEAN = "FAT_EXPORT_FOB_CLEAN";
export const FAT_FOB = "FAT_EXPORT_FOB";
export const FAT_LIST_ALL = "FAT_LIST_ALL";
export const FAT_UPDATE = "FAT_UPDATE";
export const FAT_SELECT_EDIT = "FAT_SELECT_EDIT";
export const FAT_SET_XML_FOLDER = "FAT_SET_XML_FOLDER";
export const FAT_UPDATE_SUCCESS = "FAT_UPDATE_SUCCESS";
export const FAT_CHECKOUT_SUCCESS = "FAT_CHECKOUT_SUCCESS";
export const FAT_LIST_SUCCESS = "FAT_LIST_SUCCESS";
export const FAT_DELETE = "FAT_DELETE";
export const FAT_DELETE_SUCCESS = "FAT_DELETE_SUCCESS";
export const REQUEST_FAT_FAILURE = "REQUEST_FAT_FAILURE";

export const SET_THEME_COLOR = "SET_THEME_COLOR";
export const ADD_TOAST = "ADD_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";
export const SHOW_TOAST = "SHOW_TOAST";
export const CLOSE_TOAST = "CLOSE_TOAST";

//PLOT REPORTS
export const PLOT_FAT_TIMESERIES = "PLOT_FAT_TIMESERIES";
export const GET_PLOT_FAT_TIMESERIES = "GET_PLOT_FAT_TIMESERIES";

//FIREBASE STORE
export const CAPTURE_IMAGE = "CAPTURE_IMAGE";
export const STORE_IMAGE_SUCCESS = "STORE_IMAGE_SUCCESS";
export const STORE_IMAGE_FAILURE = "STORE_IMAGE_FAILURE";
export const UPLOAD_IMAGE_PROGRESS = "UPLOAD_IMAGE_PROGRESS";
export const GET_IMAGE = "GET_IMAGE";
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
export const GET_IMAGE_FAILURE = "GET_IMAGE_FAILURE";