export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const GET_CONCILIACAO = 'GET_CONCILIACAO';
export const IMPORT_CONCILIACAO_SUCCESS = 'IMPORT_CONCILIACAO_SUCCESS';
export const GET_CONCILIACAO_SUCCESS = 'REQUEST_CONCILIACAO_SUCCESS';
export const GET_CONCILIACAO_FAILURE = 'REQUEST_CONCILIACAO_FAILURE';
export const GET_CONCILIACAO_IMPORT = 'GET_CONCILIACAO_IMPORT';

/*FATURAMENTO */
export const FAT_FECHAMENTO_READ = 'FAT_FECHAMENTO_READ';
export const FAT_FECHAMENTO_SAVE = "FAT_FECHAMENTO_SAVE";
export const FAT_EXPORT_FOB = "FAT_EXPORT_FOB";
export const FAT_LIST_ALL = "FAT_LIST_ALL";
export const SET_FAT_XML_FOLDER = "SET_FAT_XML_FOLDER";
export const REQUEST_FAT_SUCCESS = "REQUEST_FAT_SUCCESS";
export const REQUEST_FAT_FAILURE = "REQUEST_FAT_FAILURE";